"""Check sampled tokens and timing on CPU. No model download.

To test the reference: CANDIDATE_DIR=instructor pytest -q tests
"""

import os
import sys
from pathlib import Path

import pytest
import torch
from transformers import LlamaConfig, LlamaForCausalLM

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(Path(os.environ.get("CANDIDATE_DIR", ROOT)).resolve()))
from model import Model
from sample import sample


@pytest.fixture(scope="module")
def model():
    torch.set_num_threads(2)
    torch.manual_seed(123)
    source = LlamaForCausalLM(LlamaConfig(
        vocab_size=64, hidden_size=128, intermediate_size=256,
        num_hidden_layers=2, num_attention_heads=4, num_key_value_heads=2,
        max_position_embeddings=1024, attention_dropout=0.0,
        initializer_range=0.1,  # Make attention errors affect sampled tokens.
    ))
    return Model(source).eval()


# Generated by instructor/sample.py with the model above. The uncached
# starter produces the same IDs (torch 2.8.0, transformers 4.57.1).
@pytest.mark.parametrize("prompt_length, seed, expected", [
    (3, 7, [16, 59, 43, 8, 40, 49, 43, 56, 46, 30, 51, 8, 0, 23, 8, 37,
            41, 54, 49, 43, 32, 56, 59, 27, 59, 18, 18, 46, 59, 58, 61, 12]),
    (17, 19, [37, 35, 52, 56, 62, 30, 51, 14, 36, 26, 59, 26, 36, 43, 59, 23,
              59, 49, 62, 61, 0, 55, 37, 9, 63, 45, 44, 48, 59, 36, 60, 44]),
    (63, 31, [32, 62, 15, 11, 33, 4, 50, 60, 54, 1, 5, 6, 1, 6, 41, 19,
              55, 40, 25, 42, 43, 36, 6, 62, 54, 4, 32, 49, 37, 26, 57, 17]),
])
def test_sampled_tokens_match_reference(model, prompt_length, seed, expected):
    prompt = (torch.arange(prompt_length) % 61 + 3).unsqueeze(0)
    generated = sample(model, prompt, max_new_tokens=len(expected), seed=seed)
    assert generated.tolist() == [expected]


def test_later_tokens_are_faster_than_first(model):
    # A long prompt makes the first token's work much larger than one decode step.
    prompt = (torch.arange(512) % 61 + 3).unsqueeze(0)
    sample(model, prompt, max_new_tokens=2)  # Warm up both kinds of CPU kernels.
    timings = []
    generated = sample(model, prompt, max_new_tokens=16, timings=timings)
    assert generated.shape == (1, 16)
    assert len(timings) == 16
    assert all(0 < seconds < timings[0] for seconds in timings[1:]), (
        f"Per-token times in ms: {[round(t * 1000, 2) for t in timings]}"
    )
